### ISSUE TITLE
Key echo in Git Bash not working with Bluetooth 1.4 and NVDA 2022.1 and NVDA 2022.2 beta 1

### ISSUE THREAD

**Issue by GeorgeKerscher** [mltony/nvda-bluetooth-audio#10]
Starting with NVDA 2022.1, Key echo stopped working. This also happened in 2022.2 beta 1. With beta 1, I get the error sound. When I disabled Bluetooth 1.4, the key echo started working again.

**Comment by cary-rowen** [comment]
This issue is no longer reproducible so I'm closing it, if you think it's still reproducible please let me know and I'll reopen it.
