### ISSUE TITLE
Nvda 2024.1 compatibility

### ISSUE THREAD

**Issue by marlon-sousa** [mltony/nvda-bluetooth-audio#21]
Hello,

Could you generate a release with nvda 2024.1 compatibility?

I haven't been able to locate such a release, and I supose the addon distribution system, is still broken on the NVDA system.

**Comment by mltony** [comment]
Bluetooth Audio has been discontinued. You should upgrade to NVDA v2024.2 - it has similar functionality built in.

**Comment by LeoStrong23** [comment]
hello, the add-on functions such as it was compatible whit NVDA 2024.2 but NVDA allert me that it is incompatible and I have to active that add-on on my own risk. I found strange that the latest NVDA version tasted is the 2023.1. @mltony, is possible release a compatible version? I don't know what risks gives use a incompatible add-on so I continue to use it with out worries but NVDA allert me each new update. could you explane me if use this incompatible version gives problems to NVDA or it's ok and I could continue to use it. I foud this add-on very helpfully and I'll sad if it will breacks in the future. thank's for the informations and for released this great add-on!

**Comment by mltony** [comment]
Bluetooth Audio has been discontinued. Recent versions of NVDA include this functionality by default. You no longer need Bluetooth Audio addon.

**Comment by LeoStrong23** [comment]
thank @mltony ,
so NVDA now doesn't cut cuts the firsts seconds of the announcements when it is used through bluetooth headphones, doing that this add-on do?

**Comment by marlon-sousa** [comment]
Closing this as it is now clear that NVDA now supports the feature.
