### ISSUE TITLE
nvda audio does not come through bluetooth headphone when calling in skype or similar apps.

### ISSUE THREAD

**Issue by hamidrezaabroshan** [mltony/nvda-bluetooth-audio#8]
When I'm calling in skype I can not nvda's voice through bluetooth headphone but nvda's voice comes out of wired headphone and other sounds comes through bluetooth headphone.
look at this issue.
https://github.com/nvaccess/nvda/issues/4178
If I press ctrl+nvda+s and switch audio output to (my bluetooth headphone)+headset, it will resolve temporarily.
This issue may does not have related directly to this addon but this addon can be solution.

**Comment by cary-rowen** [comment]
It is not directly related to this add-on and I recommend close it.
cc @mltony

**Comment by cary-rowen** [comment]
Since nvaccess/nvda#4178 has been closed, we should close this as well.
